- name: Install nagios3
  apt: pkg=nagios3

- name: Install python-pyinotify
  apt: pkg=python-pyinotify

- name: wget Orain deb packages
  shell: wget apt.orain.org/debian/{{item}}
  with_items:
  - ircecho.deb
  args:
    chdir: /root/debs/
    creates: /root/debs/{{item}}
  changed_when: False # never report as changed
  
- name: Install Orain deb packages
  apt: deb={{item}}
  with_items:
  - /root/debs/ircecho.deb
  changed_when: False # never report as changed
