---
# python may need to be installed manually.
- hosts: all
  vars_files:
    - ../private/vars.yml
  roles:
    - common

- hosts: mediawikiservers
  vars_files:
    - ../private/vars.yml
  roles:
    - hhvm
    - nginx
    - php
    - mediawiki

- hosts: dbservers
  vars_files:
    - ../private/vars.yml
  roles:
    - mariadb

- hosts: monitoringservers
  vars_files:
    - ../private/vars.yml
  roles:
    - nagios

- hosts: staticservers
  vars_files:
    - ../private/vars.yml
  roles:
    - nfs-server
    
- hosts: mailservers
  vars_files:
    - ../private/vars.yml
  roles:
    - mail

- hosts: redisservers
  vars_files:
    - ../private/vars.yml
  roles:
    - redis

- hosts: dnsservers
  vars_files:
    - ../private/vars.yml
  roles:
    - dns

- hosts: gangliaservers
  vars_files:
    - ../private/vars.yml
  roles:
    - ganglia
