- name: Copy HHVM fastcgi script to init.d
  copy: src="hhvm-start" dest=/etc/init.d/hhvm-start owner=root group=root mode=770

- name: Add hhvm-start to boot
  command: update-rc.d hhvm-start defaults 98
  register: update_rc_hhvm
  failed_when: "'error' in update_rc_hhvm.stdout"
  changed_when: False # never report as "changed"

- name: Copy config.hdf over
  copy: src="config.hdf" dest=/etc/hhvm/config.hdf owner=root group=root mode=644
