---
- name: Reload ferm
  service: name=ferm state=reloaded

- name: Restart nrpe
  service: name=nagios-nrpe-server state=restarted

- name: Restart ganglia-monitor
  service: name=ganglia-monitor state=restarted
