- name: Copy backup.sh
  template: src=backup.sh dest=/root/backup.sh  owner=root group=root mode=770

- name: Create a cronjob for backup.sh
  cron: name="backup.sh"
        user="root"
        minute=0
        hour=0
        job="/root/backup.sh > /var/log/cron/backup.log 2>&1"