- name: Copy quickscripts
  template: src={{item}} dest=/root/{{item|basename}} owner=root group=root mode=770
  with_fileglob:
    - ./quickscripts/*

- name: Create log directories
  command: mkdir -p {{item}}
  with_items:
    - /var/log/cron/
  changed_when: False # never report as "changed"

- name: Copy ansible logrotate configuration
  copy: src="./logrotate.d/ansible" dest=/etc/logrotate.d